### ISSUE TITLE
lark isn't available unless you use pip? 

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#21]
lark doesn't seem to be part of the standard python install 

I had to do the following to get it as I got errors with a standard pip install

pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org lark

So I think the instructions for install from GitHub now involve an extra step and require the user use pip

**Comment by ivmfnal** [comment]
There are a few modules not included in standard Python library, required by MetaCat. lark (used by MQL parser) is one of them. These modules are included in the MetaCat requirements, which are installed by ``pip install`` automatically as well as when installing MetaCat from github using ``setup.py``, because ``pip install`` and ``seatup.py`` are essentially the same thing.

When I try to install from github, lark does get installed:

```
$ rm -rf ~/miniconda3/lib/python3.8/site-packages/metacat*
$ rm -rf ~/miniconda3/lib/python3.8/site-packages/lark*
$ cd ~/git/metacat
$ python setup.py install
running install
running bdist_egg
...
Searching for lark
Reading https://pypi.org/simple/lark/
Downloading https://files.pythonhosted.org/packages/ac/c7/25e678cb94ac2b7be741272d5b2ae099e32e23f36d820e6feb8931b12382/lark-1.1.5-py3-none-any.whl#sha256=8476f9903e93fbde4f6c327f74d79e9b4bd0ed9294c5dfa3164ab8c581b5de2a
Best match: lark 1.1.5
Processing lark-1.1.5-py3-none-any.whl
Installing lark-1.1.5-py3-none-any.whl to /home/ivm3/miniconda3/lib/python3.8/site-packages
Adding lark 1.1.5 to easy-install.pth file
...
$ python 
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lark
>>> 

```

**Comment by ivmfnal** [comment]
@hschellman how exactly did you try to install metacat ?

**Comment by hschellman** [comment]
I got this to work now - I'm generally doing a git clone followed by a setup.py install -user
