### ISSUE TITLE
Add ability to delete datasets via CLI, API

### ISSUE THREAD

**Issue by ivmfnal** [ivmfnal/metacat#29]

**Comment by hschellman** [comment]
Actually, perhaps ability to have status for datasets, for example retired, so that they don't show up unless you specifically ask that they be listed in queries.  I think files have something like this.  Would be nice to retire  all my old test datasets.  I think the mechanisms are already in place for files.

**Comment by ivmfnal** [comment]
What is the use case for this functionality ?

**Comment by hschellman** [comment]
The 70,000 mostly obsolete definitions in sam is an example.  

In my case, as I have been testing creation of tagged datasets, I have produced multiple copies.  So the gui is clogged with multiple useless old versions.  in the end we want to present users with clarity, so the ability to remove obsolete datasets from view would be very useful.  


Files already have this functionality, having it for datasets would be really useful.

**Comment by ivmfnal** [comment]
70000 definitions in SAM do not belong in MetaCat. Those are project definitions and they are part of the workflow management and out of scope of MetaCat. Workflow management is moved to Data Dispatcher and (I assume) to justIN. MetaCat datasets are not the same as SAM project definitions and are not supposed to be temporary objects.

As for testing/development, please use the demo instance.

You can delete unneeded test datasets yourself using GUI. Or if you give me the list of datasets you want to delete, I can do it for you going directly to the database.

**Comment by hschellman** [comment]
Those are not projects, those are the equivalent of  dataset definitions!  And thus fully within metacat.  The existence/location of files is not part of them.   And I agree  that 70,000 is too many - but my suggestion is that we retire bad ones.  As otherwise finding the good ones becomes hard.

I am trying to make metacat user-friendly - the use of namespaces makes it much nicer to isolate user activity but users/groups still need this kind of tool so that they can retire mistakes.  Which happen a lot.

I will try using the gui, but having a CLI would be extremely useful. Anything the gui can do should have an API in the end.



On Aug 28, 2023, at 6:23 AM, Igor Mandrichenko ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


70000 definitions in SAM do not belong in MetaCat. Those are project definitions and they are part of the workflow management and out of scope of MetaCat. Workflow management is moved to Data Dispatcher and (I assume) to justIN. MetaCat datasets are not the same as SAM project definitions and are not supposed to be temporary objects.

As for testing/development, please use the demo instance.

You can delete unneeded test datasets yourself using GUI. Or if you give me the list of datasets you want to delete, I can do it for you going directly to the database.

**Comment by ivmfnal** [comment]
Done. Please upgrade your client to 3.38.0
